version: '3.9'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./shop:/var/www/lt #see rootDir ./docker-conf/nginx.conf
            - ./docker-conf/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
    service_php:   #nginx listen   service_php:9000   
        build:
            context: .
            dockerfile: Dockerfile
        container_name: service_php     
        image: service_php             
        volumes:
            - ./shop:/var/www/lt 
            - ./docker-conf/docker-entrypoint.sh:/var/www/lt/docker-entrypoint.sh         
        networks:
            - my-network    
        entrypoint: /var/www/lt/docker-entrypoint.sh       
    

networks:
    my-network:
        driver: bridge