version: '3.9'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./shop:/var/www/lt #see rootDir ./docker-conf/nginx.conf
            - ./docker-conf/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - my-network
    lt_php:
        #nginx listen   lt_php:9000   
        build:
            args: 
                - arg_user=bob 
                - arg_uid=1000 
                - arg_gid=1000
            context: .
            dockerfile: Dockerfile
        container_name: lt_php
        image: lt_php
        volumes:
            - ./shop:/var/www/lt
            - ./docker-conf/docker-entrypoint.sh:/var/www/lt/docker-entrypoint.sh
        networks:
            - my-network
        entrypoint: /var/www/lt/docker-entrypoint.sh
        #docker-entrypoint.sh ==> cd /var/www/lt && composer update  
        #May be better: docker-compose exec lt_php    composer install/update?
    lt_mariadb:
        container_name: lt_mariadb
        image: mariadb
        networks:
            - my-network
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: 0000
            MARIADB_USER: lt
            MARIADB_PASSWORD: 1XfY1u9*2W-VSxHE    
            MARIADB_DATABASE: lt          
        volumes:
            - volume_lt_mariadb:/var/lib/mysql
        ports:
            - "3306:3306"     

networks:
    my-network:
        driver: bridge

volumes:
    volume_lt_mariadb:
